package com.myspace.cep_1;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@org.kie.api.definition.type.Role(org.kie.api.definition.type.Role.Type.EVENT)
@org.kie.api.definition.type.Timestamp("time")
public class ASA1311Z implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long time;

	private java.lang.Integer value;

	public ASA1311Z() {
	}

	public java.lang.Long getTime() {
		return this.time;
	}

	public void setTime(java.lang.Long time) {
		this.time = time;
	}

	public java.lang.Integer getValue() {
		return this.value;
	}

	public void setValue(java.lang.Integer value) {
		this.value = value;
	}

	public ASA1311Z(java.lang.Long time, java.lang.Integer value) {
		this.time = time;
		this.value = value;
	}

}