package com.myspace.cep_1;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@org.kie.api.definition.type.Role(org.kie.api.definition.type.Role.Type.EVENT)
@org.kie.api.definition.type.Timestamp("time")
@org.kie.api.definition.type.Duration("duration")
public class BlindingEvent implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long duration;

	private java.lang.Long time;

	private java.lang.String status;

	public BlindingEvent() {
	}

	public java.lang.Long getDuration() {
		return this.duration;
	}

	public void setDuration(java.lang.Long duration) {
		this.duration = duration;
	}

	public java.lang.Long getTime() {
		return this.time;
	}

	public void setTime(java.lang.Long time) {
		this.time = time;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public BlindingEvent(java.lang.Long duration, java.lang.Long time,
			java.lang.String status) {
		this.duration = duration;
		this.time = time;
		this.status = status;
	}

}