package com.myspace.cep_1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class sci implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private Long duration;
	private Long time;

	public sci() {
	}

	public java.lang.Long getDuration() {
		return this.duration;
	}

	public void setDuration(java.lang.Long duration) {
		this.duration = duration;
	}

	public java.lang.Long getTime() {
		return this.time;
	}

	public void setTime(java.lang.Long time) {
		this.time = time;
	}

	public sci(java.lang.Long duration, java.lang.Long time) {
		this.duration = duration;
		this.time = time;
	}

}